version: "3.9"
services:
  mlflow:
    image: continuumio/miniconda3
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model
      - ./log:/log
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: pip install mlflow && mlflow models serve -m /app/model -p 5000 -h 0.0.0.0
